name:                clase
version:             0.1.0.0
github:              "githubuser/clase"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Clase de PdeP.

dependencies:
- base >= 4.7 && < 5
- pdeprelude
- hspec

default-extensions:
  - NoImplicitPrelude
  - FlexibleContexts
  - RebindableSyntax

library:
  source-dirs: src
  other-modules: []

tests:
  clase-test:
    main:                CorrerTests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clase

